{% set name = "nionswift-video-capture" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7bc4226f8b87b70b59e911b56b745f00ff1563b12c2227dae424e7ad7fefca22

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - nionswift >=16.9.0,<17.0.0
    - nionswift-instrumentation >=22.0.0,<23.0.0

test:
  imports:
    - nionswift_plugin.nionswift_video_capture

about:
  home: https://github.com/nion-software/nionswift-video-capture
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Capture video from built-in camera using OpenCV.
  dev_url: https://github.com/nion-software/nionswift-video-capture

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
