{% set name = "nionswift-video-capture" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f849efba39f14b0fb14506e039c46ffb6b7796794886df143ab230c43df07a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - nionswift-instrumentation >=0.20.0,<0.21
    - opencv
    - python >=3.8

test:
  imports:
    - nionswift_plugin.nionswift_video_capture

about:
  home: https://github.com/nion-software/nionswift-video-capture
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Capture video from built-in camera using OpenCV.
  dev_url: https://github.com/nion-software/nionswift-video-capture

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
